### ISSUE TITLE
Change JPL CH4 plumes dataset to non-periodic

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#14]
Following up on https://github.com/NASA-IMPACT/veda-data-pipelines/issues/357

Collection: `jpl-ch4-plume-emissions`

https://deploy-preview-6--ghg-demo.netlify.app/data-catalog/jpl-ch4-plume-emissions/explore?position=-94.8438%7C30.2093%7C15.53&datetime=2022-08-11T00%3A00%3A00.000Z

## Acceptance criteria

- [x] Dataset is no longer configured as periodic
- [x] Verified that only existing dates show up in the Dashboard date selector for this dataset

**Comment by slesaad** [comment]
the dataset is updated to be non-periodic, and the behavior (with my minimal testing) looks good in the dashboard.
