### ISSUE TITLE
Links in text are hard to identify as such

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#143]
Reviewers commented that text links like the one below are hard to identify as such, because they do not stand out against the main text.

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/b9182a1e-1ace-47a7-9920-218ca8d6ed1d)

Is that intended or would it make sense to make them more visible?

## Acceptance criteria

- [ ] Addressed request

**Comment by faustoperez** [comment]
I think this inherits from the main accent color which is also used in the headers. 

@danielfdsilva is it possible to change the link color (only) without changing the header color? These are the changes needed to pass accessibility:

- Text color to #1B2631 -> reduce lightness
- Link color to #1565EF -> increase lightness

https://webaim.org/resources/linkcontrastchecker/?fcolor=1B2631&bcolor=FFFFFF&lcolor=1565EF

<img width="761" alt="image" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/12268629/52413f87-0c62-48f0-81a3-3020e478a094">

**Comment by danielfdsilva** [comment]
@faustoperez Yes! This is very easy and is done through the theme. PR https://github.com/NASA-IMPACT/veda-config-ghg/pull/150
