### ISSUE TITLE
Turn off debug logs for UI

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#152]
@amarouane-ABDELHAK asked me to ticket that we turn off the debug log messages in the GHG instance of VEDA UI.

Not sure where these come from and where that setting is made - but perhaps you do?

## Acceptance criteria

- [ ] No more debug messages in the staging and production deployments of the GHG UI

**Comment by amarouane-ABDELHAK** [comment]
We have some `console.log` and `console.groupCollapsed` activated in the GHG instance of VEDA UI (staging and production)
Can we at least not show these logs in production (https://ghg.center/) 
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/33136280/f25d2432-2746-4436-af8d-4acb1fafa523)

**Comment by j08lue** [comment]
@nerik identified the culprit to be this: https://github.com/NASA-IMPACT/veda-ui/blob/main/app/scripts/components/common/mapbox/layers/raster-timeseries.tsx#L36 and has fixed it in https://github.com/NASA-IMPACT/veda-ui/pull/679/commits/e00951a3f392ffb4bc4ca913132b0baa6c82142a
