### ISSUE TITLE
Publish EPA tabular data in a data story

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#16]
There are probably a couple of tabular data overviews (emissions by country etc) that the GHG Center would like to feature.

To begin with perhaps as Data Stories.

The first dataset to publish is from EPA GHG reporting (https://www.epa.gov/ghgreporting/data-sets), specifically the [2021 Data Summary Spreadsheets (zip)](https://www.epa.gov/system/files/other-files/2022-10/2021_data_summary_spreadsheets.zip)).

## Acceptance criteria

- [ ] Configured a data story that displays the selected EPA dataset

**Comment by hanbyul-here** [comment]
The data consists of multiple sheets. What is the expectation here? Should we show the data from all the sheets?

**Comment by j08lue** [comment]
@hanbyul-here, are you blocked by the decision about which sheets from the data file to present, or have you been able to work on a feature using any of them?

**Comment by hanbyul-here** [comment]
@j08lue no. my progress was slower than I hoped. you can review the table in this pr now: https://github.com/NASA-IMPACT/veda-ui/pull/597

**Comment by danielfdsilva** [comment]
A new [Table block](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/MDX_BLOCKS.md#table) was added for MDX content

**Comment by j08lue** [comment]
Great we have the component in place! We still need a story or dataset info page that includes this data, no?

**Comment by j08lue** [comment]
Will open new tickets to fine-tune table component once we have target data.
