### ISSUE TITLE
Change order of stories - via publication date?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#181]
Stories ("Data Insights") are currently sorted alphabetically, resulting in this order:

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/0c277ab9-7636-4d73-aa4e-75c867eafeb2)

Since we have one story per thematic area plus one intro story, it would be great to sort the stories in this order instead:

1. U.S. Methane Sources [Anthropogenic]
2. Tracking Greenhouse Gas Cycles [Natural]
3. Discovering Large Methane Emission Events with Remote Measurement [Methane emissions]
4. Intro to the US GHG Center

While the app currently does not support arbitrary ordering, could we
1. Sort by date by default (most recent first)
2. Set the publication dates on the stories such that they come in the right order?

## Acceptance criteria

- [x] Stores appear in the indicated order

**Comment by j08lue** [comment]
> This ticket wants to switch the default sorting to publication date with most recent coming first correct?

Yes! @danielfdsilva agreed that this would be a sensible default and we can just make that stick across all instances (i.e. not configurable but in veda-ui).

> can you clarify "Set the publication dates on the stories such that they come in the right order"

Sure! We would like the currently existing four stories to show in this order:

1. U.S. Methane Sources [Anthropogenic]
2. Tracking Greenhouse Gas Cycles [Natural]
3. Discovering Large Methane Emission Events with Remote Measurement [Methane emissions]
4. Intro to the US GHG Center

Their publication date is somewhat arbitrary, so we can just change that for all the four stories so that they by default (ordered by recency) show up in this order.

https://github.com/NASA-IMPACT/veda-config-ghg/blob/00b242e8473e95781d44b75b6c83cae72e6089fb/stories/discovering-large-methane-emissions.stories.mdx#L10

**Comment by sandrahoang686** [comment]
[PR to VEDA UI to update default sorting](https://github.com/NASA-IMPACT/veda-ui/pull/706)

**Comment by sandrahoang686** [comment]
[PR to veda-config-ghg](https://github.com/NASA-IMPACT/veda-config-ghg/pull/208) to update sorting of stories based on this issue
