### ISSUE TITLE
GHG design updates October

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#204]
From stakeholder feedback, we got a few small suggestions for design changes.

1. Make highlighted layer more clear (contrast to panel background gray)
   ![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/eac1faed-ced6-4dea-b07a-d1b0dc32dbae)

2. Remove trailing "Overview" from dataset titles
3. https://github.com/NASA-IMPACT/veda-config-ghg/issues/207

## Acceptance criteria

- [ ] Responded to the points above, either directly or in the context of a larger design update

**Comment by deborahUAH** [comment]
I am suggesting to either do something like this:
_Overview of_
Gridded Anthropogenic Methane Emissions Inventory

or like this
Gridded Anthropogenic Methane Emissions Inventory
_Overview_

**Comment by deborahUAH** [comment]
or we can just omit Overview from the title completely

**Comment by j08lue** [comment]
Ahh, now I get it. It's not about the menu on the right but about the word added to the titles... Thanks for the clarification.

**Comment by faustoperez** [comment]
Hi, here's the updated design to make the Overview + Exploration and layer selection more clear.

<img width="1728" alt="US GHG Center - Exploration" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/12268629/4734e00b-d23c-4bd7-bb80-548e7e43c207">

### These are the changes:

- Remove the white separator on the header
- Style the Overview + Exploration as tabs
- On the layers panel, use the link color as a background for the active layer state, and change the text color to white
- Set text weight to Regular
- Add a 1px gray line at the bottom to separate items
- Make the layer title wrap to the next line (do not truncate)
- Show information icon only on hover / active to reduce clutter
- On hover, change background to light gray (same as now)

**Comment by j08lue** [comment]
If this styling change is quick enough to implement, I think we should do that, despite the ongoing work to replace the complete feature, because it would improve the current user experience while we build and test the new.

**Comment by faustoperez** [comment]
If it helps the estimation, the 2 CSS changes are 

- Navigation tabs
- Sidebar layer list elements.

**Comment by j08lue** [comment]
Does the change of logo order

- https://github.com/NASA-IMPACT/veda-config-ghg/issues/210

require design guidance?

**Comment by faustoperez** [comment]
> Does the change of logo order require design guidance?

I don't think it does 🙂
