### ISSUE TITLE
Change logo order throughout the platform to NASA, EPA, NIST, NOAA

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#210]
After programmatic review, it has been decided that the logo order throughout the GHG Center needs to be **NASA, EPA, NIST, NOAA**, to indicate the role NASA took in creating the center.

This needs to be changed in

- [x] Landing page - top and bottom https://github.com/NASA-IMPACT/veda-config-ghg/pull/213
- [x] Footer https://github.com/NASA-IMPACT/veda-config-ghg/pull/213
- [x] About page partner logo and text snippet order https://github.com/NASA-IMPACT/veda-config-ghg/pull/213
- [x] Login page for hub [https://hub.ghg.center/](https://hub.ghg.center/) https://github.com/US-GHG-Center/ghgc-hub-homepage/pull/14
- [x] Top of feedback form https://github.com/NASA-IMPACT/veda-config-ghg/pull/223
- [x] Greenhouse gas center introduction data insight [banner image, text bullets, top of "who's behind the US GHG Center" section, and replace screen capture of feedback form once logos re-ordered] https://github.com/NASA-IMPACT/veda-config-ghg/pull/223

**Comment by deborahUAH** [comment]
- [ ] landing page  -  top and bottom
- [ ] Footer
- [ ] about page partner logo and text snippet order
- [ ] login page for hub [https://hub.ghg.center/](https://hub.ghg.center/) 
- [ ] top of feedback form 
- [ ] greenhouse gas center introduction data insight [banner image, text bullets, top of "who's behind the US GHG Center" section, and replace screen capture of feedback form once logos re-ordered]

**Comment by sandrahoang686** [comment]
Note:
* Google forum needs to be updated here https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform

**Comment by sandrahoang686** [comment]
@j08lue Given the requirements of needing to change the order for the last bullet. Do we have new assets with this new order?

For example, there currently exists the `stories/intro-to-ghg-center--cover.png` and `stories/logos.png` which lives in `veda-config-ghg` and is used for the last bullet point ```Greenhouse gas center introduction data insight [banner image, text bullets, top of "who's behind the US GHG Center" section, and replace screen capture of feedback form once logos re-ordered]```

**Comment by j08lue** [comment]
Maybe @faustoperez can include the logo series plus the hero image in Figma and we can grab them from there?

**Comment by faustoperez** [comment]
Please grab the assets from https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=498%3A561&mode=design&t=V06kTgRMSPDMQR87-1

The logos are ready to be exported in svg, 1x and 2x pngs.

The hero image is a snapshot of the video, it has to be added with a `lighten` blending mode in CSS so it works better with the dark blue background.

Let me know if this works on your side 🙂

**Comment by j08lue** [comment]
Complete.
