### ISSUE TITLE
Set up preview of E&A on the GHG Center UI

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#216]
For testing and user interviews, it would be helpful to have the new Exploration & Analysis feature deployed on the GHG Center instance (in preview or staging), so testers can use the interface with real(istic) GHG Center datasets.

## Acceptance criteria

- [ ] An E & A interface is available for testing with the real GHG Center datasets in a non-public place

**Comment by danielfdsilva** [comment]
Preview link: https://deploy-preview-217--ghg-demo.netlify.app/exploration
