### ISSUE TITLE
Add feedback form to GHG instance

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#22]
VEDA for GHG needs its own feedback form to be shown under the same link as VEDA for NASA/EIS:

<img width="975" alt="image" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/e98629e7-9fc1-43c9-8e3d-77a548005b7d">

## Acceptance criteria

- [x] Received feedback form link from @Jeanne-le-Roux 
- [ ] Configured feedback form link in VEDA for GHG instance - feedback menu item shows up on all pages

**Comment by Jeanne-le-Roux** [comment]
Here's the link: https://forms.gle/zEoY3WMbEJ9uxvEj6

The form itself may get modified but I don't think this will effect the link.
