### ISSUE TITLE
Fossil Fuel CO₂ Emissions analysis causes 500 on /statistics

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#232]
For example in this analysis:

https://earth.gov/ghgcenter/analysis/results?start=2021-01-01T00%3A00%3A00.000Z&end=2022-12-31T00%3A00%3A00.000Z&datasetsLayers=co2-emissions&aoi=~fsia%40%3F%3F_ye~O_ol%7BU%3F%3F~xe~O

an example request causing a 500 when called from the frontend app is a POST request to https://ghg.center/api/raster/cog/statistics?url=s3://ghgc-data-store/odiac-ffco2-monthgrid-v2022/odiac2022_1km_excl_intl_202105.tif

![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/ae03696f-1d9a-46fb-92ad-d00b980b2a0a)

Please note: understanding and documenting this issue is the most critical part. Fixing it can come after the release, if it shows that we do not have the time before.

cc @anayeaye @hanbyul-here 

## Acceptance criteria

- [x] Figured out what is causing this
- [x] Opened a ticket to fix it

**Comment by anayeaye** [comment]
**Reproducible error**
request `https://ghg.center/api/raster/cog/statistics?url=s3://ghgc-data-store/odiac-ffco2-monthgrid-v2022/odiac2022_1km_excl_intl_202108.tif`
payload 
```
{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[-180,0],[-180,89],[-60,89],[-60,0],[-180,0]]]]}}
```

failing request to reproduce memory errors observed in raster-api log above
```
curl -X 'POST' \
  'https://ghg.center/api/raster/cog/statistics?url=s3://ghgc-data-store/odiac-ffco2-monthgrid-v2022/odiac2022_1km_excl_intl_202108.tif' \
  -H 'accept: application/geo+json' \
  -H 'Content-Type: application/json' \
  -d '{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[-180,0],[-180,89],[-60,89],[-60,0],[-180,0]]]]}}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168  100    34  100   134      2      8  0:00:17  0:00:15  0:00:02     8
{
  "detail": "Internal Server Error"
}
```

**Comment by anayeaye** [comment]
The search geometry is fine. The dataset is VERY high resolution. 

The request works with a much smaller geometry. 
```
curl -X 'POST' \
  'https://ghg.center/api/raster/cog/statistics?url=s3://ghgc-data-store/casagfed-carbonflux-monthgrid-v3/GEOSCarb_CASAGFED3v3_FIRE_Flux_Monthly_x720_y360_200301.tif' \
  -H 'accept: application/geo+json' \
  -H 'Content-Type: application/json' \
  -d '{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[-118.98917,44.80303],[-108.08194,43.97778],[-109.75011,37.16468],[-119.37413,36.85728],[-118.98917,44.80303]]]]}}' | jq
```

**Comment by anayeaye** [comment]
## Solution
**`max_size=1024`** path parameter (thanks @vincentsarago!) 

```
curl -X 'POST' \
  'https://ghg.center/api/raster/cog/statistics?url=s3://ghgc-data-store/odiac-ffco2-monthgrid-v2022/odiac2022_1km_excl_intl_202108.tif&max_size=1024' \
  -H 'accept: application/geo+json' \  
  -H 'Content-Type: application/json' \
  -d '{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[-180,0],[-180,89],[-60,89],[-60,0],[-180,0]]]]}}'


{"type":"Feature","geometry":{"type":"MultiPolygon","coordinates":[[[[-180.0,0.0],[-180.0,89.0],[-60.0,89.0],[-60.0,0.0],[-180.0,0.0]]]]},"properties":{"statistics":{"b1":{"min":-127.76295471191406,"max":1422.452392578125,"mean":0.9611924020867598 <SNIP>
```

@hanbyul-here can this parameter be added to the analysis request? I think it could be OK to use for all datasets.

**Comment by j08lue** [comment]
Opened a ticket to fix this:

- https://github.com/NASA-IMPACT/veda-ui/issues/765

**Comment by dzole0311** [comment]
To follow-up on this as it looks related, I noticed that choosing Delaware and running the analysis, the Air-Sea CO₂ Flux dataset errors out with 500 on the `statistics` endpoint.

It can be [reproduced here](https://earth.gov/ghgcenter/exploration?datasets=%5B%7B%22id%22%3A%22air-sea-co2%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&date=2022-11-30T23%3A00%3A00.000Z&aois=%5B%22bqnmMwfmqFm_Cu%7EEaaFsuE%7BqI%7BtDgkLiqA_JaAuoAqNsx%40aJslPn%7D%40m%7CKliDjtGt%60FvpBn%7CHrgErsDv%7DCbrFzvCvkBw_BhrEebEnoBj%7CA%7EiGrAfgFbuKhuBwcCxzFmxH%7C%7DHgcBdlB_bFjvF%7D%7BJf%7CK%7BsAb%7CMfnAptI%7DdAzxMeyI%60lF_uEzbMsXbu%40pHn%60DiaMrmLigMzpIq%7CG%7Ek%40ctCwwAmmBjtRmnBjh%5Eo%5EhrOftYp%40%7Cl%5D%7BGn%7DY%7BFf%7Bh%40eg%40rh%40icOtGuoBbc%40aqM%3FId%60Bg%7Ed%40p%7BCce%7C%40vr%40gfS%60XcxHhg%40mwN%40%5DpfCmhbA%22%2C%2274350%22%2Ctrue%5D&selectedForEditing=false&dateRange=2022-09-30T22%3A00%3A00.000Z%7C2022-12-31T23%3A00%3A00.000Z).
