### ISSUE TITLE
Release version with new error title to production

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-config-ghg#271]
# Description
The "Critical Error" sounds more alarming than it is. We'd like to change the title to something less alarming -  there is nothing critical about this error and the low occurrence also makes it not critical. 
The change has already been made to `veda-ui` but we still need to release it to the GHG center website.
The plan is to release it early next week (after AMS)

# Acceptance Criteria
- [x] New version of GHG Center released which includes above mentioned change

**Comment by hanbyul-here** [comment]
GHG needed a hotfix deploy, and shipped this change along with the fix. 
Closed with https://github.com/NASA-IMPACT/veda-config-ghg/pull/287
