### ISSUE TITLE
Review Lighthouse report

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-config-ghg#272]
# Description
The lighthouse report for GHG Center looks pretty good. But there are still some recommendations that make it even better. It'd be nice if we reviewed the report and addressed some low-hanging fruits to make it even better.
Maybe even add documentation that content editors can follow about media recommendations.

# Acceptance Criteria
- [ ] Lighthouse report reviewed and new tickets created for improvements

**Comment by j08lue** [comment]
Related ticket, FWIW

- https://github.com/NASA-IMPACT/veda-ui/issues/11

**Comment by j08lue** [comment]
Actually a duplicate / revisit of

- https://github.com/NASA-IMPACT/veda-ui/issues/688
