### ISSUE TITLE
Remove summer school banner

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#282]
The deadline announced on the current banner has passed.

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/b210a7ed-47b9-4035-a402-1fa8d14045b3)

## Acceptance criteria

- [x] Removed banner in production deployment

**Comment by slesaad** [comment]
https://github.com/NASA-IMPACT/veda-config-ghg/pull/283
