### ISSUE TITLE
Display JSON files for Plume dataset

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-config-ghg#32]
High priority ask from EMIT Team. JPL has provided JSON files for all plume tiff files. Need to display JSON files on the dashboard. In several cases, plume observations overlap each other and in order to distinguish between plumes, the boundaries need to be shown. 
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/98853455/c8924524-0b63-4cff-a1cf-41a5a46bd08b)

**Comment by aboydnw** [comment]
@jerikac @deborahUAH @Jeanne-le-Roux can you add this to the [Release 1 Schedule](https://docs.google.com/spreadsheets/d/1u5eYDI_EmL3sSttYkTm91_lEeK2tFsgXH3D22wczmrA/edit#gid=88759098) spreadsheet, add a priority and rank appropriately? That will help us prioritize against all the other issues

**Comment by aboydnw** [comment]
@Jeanne-le-Roux @jerikac @deborahUAH I saw this was given a priority 1 in the spreadsheet, which came as a bit of a surprise to me. Do we know how many cases of plume overlap there are, compared to the total number of observations? It feels like a bit of an edge case to me, but I may be wrong.

I ask because, the ability to stack multiple layers on top of one another is functionality that is planned for the upcoming exploration/analysis rework. So, I would be hesitant to implement a temporary solution now for an edge case when we have plans for a more elegant solution in the near future.

**Comment by j08lue** [comment]
We discussed this at the Dashboard tag-up / catch-up today, to be refined with @aboydnw later today. Preliminary decision:

We discussed previously that the Dasboard's generic Exploration UI is not very well suited for providing all the annotations that exploration of plume emission data requires. It's strength is the standardized analysis of standard (raster, for now) datasets.

To tailor to the needs of presenting the plume dataset, we should instead create a customized UI for plume data (as a case for https://github.com/NASA-IMPACT/veda-architecture/issues/290#issuecomment-1671811531, similar to https://visex.netlify.app/stories/recent-fires).

If we agree on this way forward, we need to find someone to create a custom UI for the plume data. Could be as a WASM-compiled Jupyter Notebook (cc @jsignell) or a simple customized map page (cc @danielfdsilva).

If we need to surface the plume outlines (and metadata) anywhere, we should probably also add that data either to the STAC entries for the raster data or to an auxiliary vector dataset in the VEDA Features API for GHG Center.

**Comment by j08lue** [comment]
> JPL has provided JSON files for all plume tiff files

Are these JSON files available anywhere already, for us to see what they contain and how we could serve them? Do they contain plume properties like average concentration etc or where would we get that information from?

**Comment by j08lue** [comment]
For the record, I received the dataset from @siddharth0248 and shared it internally with the team.
