### ISSUE TITLE
 Replace GHG logo with the 4 partner agency logos at the top of the landing page (favicon too?)

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-config-ghg#42]
The current GHG Center Logo used on the landing page, and as the favicon has not been approved and should not be used for the first Release... for now, the ask is to replace the logo on the top left of the landing page (see below) with the 4 partner agency logos (EPA, NASA, NIST, NOAA).

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/98853455/345e17eb-57fa-48cb-97d6-d30ef9b057d0)

**Comment by jerikac** [comment]
@aboydnw this request may also require a change of the favicon, which current displays the logo we've created... I don't know what icon we would use instead.. 
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/98853455/02f7e8db-263c-4e19-8076-141a92a0250e)

**Comment by aboydnw** [comment]
We should discuss this in a checkin. I don't think it makes sense to include all four logos in a logo/favicon like this. The only way to do that would be to make each logo illegible. Which, we could do with a 2x2 grid of the 4 logos, but it's not a very effective logo in that case.

**Comment by aboydnw** [comment]
You could imagine something like this, it would be pretty illegible in this format. (this is also partly why we suggested such simple logos previously, and are curious about the additional elements recently added to them)
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/92742765/1545d23f-5f9d-4e9b-80bd-cfff16e3de75)

**Comment by jerikac** [comment]
Agreed. It might take some playing with to find a solution.

**Comment by Jeanne-le-Roux** [comment]
@aboydnw Just curious, can the 4 logos be displayed on the top navigation bar somewhere next to each other? Or is there just a placeholder for a single image/icon?

**Comment by danielfdsilva** [comment]
That's correct @aboydnw. If a logo can't be found for the project, might be better to just have a name, and then displaying the partner logos in the footer, for example, and in the about page with more detailed information.

**Comment by j08lue** [comment]
We found a different solution, which was accepted.
