### ISSUE TITLE
Feedback on Landing Page Aug 11 2023

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-config-ghg#43]
We had a meeting with Shanna from NASA where we went over the GHG dashboard with a focus on the landing page. Here are some notes on the feedback given (full notes [here](https://docs.google.com/document/d/1JrjpHfnZ5cG8YjFxg5u3b7xZsLKiungA_UiFMRJs2yc/edit#heading=h.hkeh2gkq6gop))

1. There were some comments on the content (for example calling it "Natural GHG Sinks" as opposed to "Sources") Is it safe to assume that these changes will be owned by @deborahUAH or @siddharth0248 ?
2. Shanna gave some good feedback about the priority of information on the landing page. These are listed below.

1. Multiagency collaboration. This leads to logo requests like [this](https://github.com/NASA-IMPACT/veda-config-ghg/issues/42), but the overall request is for logos to be front and center. This ties to content as well, Shanna wants to make sure it is very clear that this is a multi agency effort.
2. Next, Shanna likes the idea of seeing, "What’s going on in the world of GHG?" This could be an interactive map of a cool dataset, or some curated data. She also gave the idea of showing a feed of GHG-related news, or at least linking to interesting articles posted elsewhere by the partner orgs. There could be a new component laying in there, or just a list of links. If we do anything with this feedback, we will need a lot of help defining what data to show and we should know it probably won't be some automatically updating mechanism like Shanna was hoping for.
3. Instead of static images, link right into workflows for people. Some of the feedback here was content-related (for example redundancy in the static images on the [demo](https://deploy-preview-30--ghg-demo.netlify.app/) site) but in general she wanted to enable users to go straight from the landing page to exploring a dataset. This is similar to feedback we have had in the past and matches what we want to do with this landing page, so it's just about finding how to do this in line with the content. She also mentioned that if we keep the format with the images explaining how to use the dashboard at the bottom of the page in this [demo](https://deploy-preview-30--ghg-demo.netlify.app/), then she would prefer them to be gifs and when you click on the gif she was expecting it to take her to the exploration page (or whatever page the gif is depicting)
4. Combine Partnerships with About page (currently two separate links)
5. Make the feedback mechanism much more prominent. She was able to find the Feedback button, but had two comments. 1) it was combined with the report a bug workflow which she didn't like. 2) it was not prominent enough. She wanted it to come across more like, "hey, thanks for coming to the dashboard, it's still in beta and we need your feedback!" She had some other comments about how a google form looks, but probably not much we could do there in a short time.

@deborahUAH @jerikac @Jeanne-le-Roux @siddharth0248 did I miss anything?

I think next steps would be assessing what to do with this information in collaboration with @danielfdsilva @j08lue and team. In my mind, we could implement fairly lite versions of most of the feedback given above, it more comes down to what content can we pull together in a short time. Shanna did say that she liked the overall aesthetic of the page, so I really don't think we are too far off.

**Comment by Jeanne-le-Roux** [comment]
1. Yes - this is just adjusting of the wording and we will take care of that. 
3. I figure we can find ways to more prominently display the agency logos throughout the site that isn't just tied to the primary logo. Working to get feedback on this. 
4. I did like her idea of incorporating the Keeling curve (https://keelingcurve.ucsd.edu/) on the home page somehow. Curious to know what the science leads would think of this. I do think we'll have to have some sort of news/announcements feature that can be a part of the home page but the specifics of how this should work should probably be scoped out post-release 1 (unless we get some very clear guidelines).
5.  If we advertise other features of the site (e.g. data catalog) I would definitely expect it to link to that component of the site. We got some mixed feedback on weather or not to include this - @deborahUAH and others will be working to better refine the home page content leading up to the release. 
6. I say let's just go ahead and combine the pages. @deborahUAH what do you think? If we keep them separate then the partnerships page can't be hidden the way it is now. 
7. Slesa did jazz up the feedback form a bit. I'm wondering if we need 2 types of forms - 1 prominent one along the lines of "We need your feedback" and then a more low key one elsewhere which is the general bug report. Or we use just 1 form but present it a couple of different ways on the site. 

Also relieved to hear there weren't major concerns about aesthetics!  

Another note I have is to look into whether the banner image can be a moving image.

**Comment by j08lue** [comment]
Most of this feedback incorporated into recent redesign.

The rest will be superseded by the upcoming next round of feedback.
