### ISSUE TITLE
Change default map projection for explore view

### ISSUE THREAD

**Issue by Jeanne-le-Roux** [NASA-IMPACT/veda-config-ghg#44]
Sourish from the GSFC team made a comment during the 8/15 tag up when testing the preview site that he wasn't a fan of Mercator being the default map projection on the explore view. He followed up with these comments via email:

"Yesterday I raised a question about the default map projection to use for displaying global datasets. Someone mentioned that if the most common user was a non-technical person, then they would be most used to the Mercator projection. I do not think this is true anymore, and hasn’t been true for some time. Most mass media outlets have moved away from the Mercator projection. For example, if you Google image search “world covid map”, most of the top results (CNN, NPR, Bloomberg, NY Times, Washington Post) are using something other than the Mercator projection (ironically, the first three maps using Mercator projection in my search results were from the Univ of Minnesota, Harvard, and Georgetown Univ, people who should know better). Even NASA’s earth science results use something else, e.g., search for “nasa heat map”.

Given that, I think it would be better to choose another map projection as the default for global datasets, such as Natural Earth or Winkel Tripel or Equal Earth."

Adding this issue so we can take his feedback into account. 

The question was also posed as to whether different default map projections could be set for different datasets. I could see it potentially being confusing to a user to be presented with different default projections on the same site, but if we find there is a need for this it can be a separate ticket.

**Comment by j08lue** [comment]
I was looking for the available `TileMatrixSets` (the `/TileMatrixSets` [endpoint](https://developmentseed.org/titiler/endpoints/tms/#tilematrixsets)) on our current TiTiler instances for NASA/EIS and GHG, but it seems like that endpoint does not exist on our instances.

https://staging-raster.delta-backend.com/docs
https://ghg.center/api/raster/docs

@anayeaye and @vincentsarago - can you inform what TileMatrixSets our TiTiler currently supports and whether it would be possible to give the user / client the possibility to choose from a few available options or perhaps even change the default, without big consequences for the web application (VEDA Dashboard)?

**Comment by vincentsarago** [comment]
@j08lue can you point me toward the codebase for those tiler? I see the TMS endpoints are added to the impact-tiler https://github.com/NASA-IMPACT/impact-tiler/blob/aa04961865c270f52b7ffe9617ca39707514368d/infrastructure/lambda/application.py#L74-L75 so I guess both tilers are not using this

**Comment by j08lue** [comment]
The codebase for the tilers in VEDA/GHG is this: https://github.com/NASA-IMPACT/veda-backend/blob/a885d0fea9fa0a014310bcce9bb66a892b1f0b24/raster_api/runtime/src/app.py

Thanks for the pointer to the TMS!

**Comment by j08lue** [comment]
@danielfdsilva tells me that out web map client library (Mapbox) actually does not support reading data in other projections than Web Mercator, but has options (that we already expose, although they are a bit hidden) to reproject the data client-side. The choice of (Mapbox-provided) projection is even configurable on a dataset level.

I will let the OP know that he can choose from the available options in Mapbox to render his dataset with that projection by default. On a related note, we are also looking into making the basemap configurable in the same way.

**Comment by j08lue** [comment]
Today at the GHG Center science meeting, the advisors made the call that `Natural Earth` or `Equal Earth` would be best, but since they have a lot of whitespace around the map when zoomed out, `Equirectangular` would probably be preferred.

https://ghg-demo.netlify.app/data-catalog/odiac-ffco2-monthgrid-v2022/explore?datetime=2000-01-01T00%3A00%3A00.000Z&projection=equirectangular%7C%7C&position=-20.0171%7C10.4089%7C2.51

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/4cb95a46-d8fe-4684-bece-af38241dc204)

@danielfdsilva, I take it the application-wide default projection cannot be changed, right? 

Then we would instead need to add the projection `Equirectangular` to all configured datasets, as described in the docs:

https://github.com/NASA-IMPACT/veda-ui/blob/71be3222ea27c8676c5ddf9c2cfc676c4f6b06dc/docs/content/frontmatter/layer.md#projection

**Comment by danielfdsilva** [comment]
@j08lue That is correct

**Comment by j08lue** [comment]
Not yet complete.
