### ISSUE TITLE
Create custom UI for EMIT plume data exploration

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#50]
The study of GHG emission plumes involves different information and interactions / workflows than standard raster or vector data browsing:

1. Plumes are transient, localized features
2. The emissions still have spatial extent (a small cloud), but it is very limited
3. A plume has specific parameters, like average emission concentration, etc.
4. There can be several plumes on the same day that overlap (https://github.com/NASA-IMPACT/veda-config-ghg/issues/31)

Displaying these custom information and browsing sub-daily plumes goes beyond the generic functionality of the VEDA Dashboard Exploration and Analysis. Can we instead build a lightweight tool for this data in particular, similar to the prototype [EIS Fire tool](https://github.com/NASA-IMPACT/veda-interactive-fire)?

The workflow the tool should support is:

- [ ] User can see locations (center locations or outlines) for all plumes that occurred within a date range within current map view or so, so they can find incidents of interest to them
- [ ] User can view the raster data for a specific plume, so they can understand the spatial extent and concentration spread
- [ ] User can see physical parameters (TBD) for a specific plume

## Data sources

- EMIT raster data collection in GHG STAC `emit-ch4plume-v1` https://e6v7j4ejp6.execute-api.us-west-2.amazonaws.com/api/stac/collections/emit-ch4plume-v1
- Polygon outlines of every plume https://drive.google.com/file/d/1f9HCtAOUiSDTiesbJrt8E9Oi9wr6e8XT/view?usp=sharing
- Parameters / properties for each plume? - included in the feature properties

## Related issues

- https://github.com/NASA-IMPACT/veda-ui/issues/588
- https://github.com/NASA-IMPACT/veda-config-ghg/issues/32
- https://github.com/NASA-IMPACT/veda-config-ghg/issues/31
- https://github.com/NASA-IMPACT/veda-ui/issues/603

## Acceptance criteria

- [ ] Created a custom UI for EMIT plume data exploration and embedded it into a GHG page

**Comment by j08lue** [comment]
The raster data is served via TiTiler here: https://ghg-demo.netlify.app/data-catalog/jpl-ch4-plume-emissions/explore?datetime=2022-08-10T00%3A00%3A00.000Z

You can grab the WMTS or XYZ links from the map icon on the right - for a specific date/mosaic:

* https://2qncpyg24c.execute-api.us-west-2.amazonaws.com/api/raster/mosaic/tiles/783f5d49ad7620050e94b6b1dd6d78e4/WebMercatorQuad/{z}/{x}/{y}@1x?assets=ch4-plume-emissions&resampling=bilinear&bidx=1&colormap_name=plasma&rescale=1%2C1500&nodata=-9999
* https://2qncpyg24c.execute-api.us-west-2.amazonaws.com/api/raster/mosaic/783f5d49ad7620050e94b6b1dd6d78e4/WMTSCapabilities.xml?assets=ch4-plume-emissions&resampling=bilinear&bidx=1&colormap_name=plasma&rescale=1%2C1500&nodata=-9999

**Comment by anayeaye** [comment]
Thanks for creating this meta ticket, I've been following but there are so many places to reply that I will just start here.

For the issue of the temporally and spatially sparse EMIT data, our existing tools would support this pattern:

1. The dashboard makes a stac/item/search for all matches within a temporal range (24 hours? a week?)
2. The result of a stac item search is a feature collection of item footprints, each with item datetime and id properties. These can be loaded directly on a map
3. A user selects a footprint. For the selection we have enough information to construct a tile url for that exact item using the collection and item id `/api/raster/stac/tiles/{TileMatrixSetId}/{z}/{x}/{y}@{scale}x.{format}`

This may not be the best fit for the problem but I wanted to make sure to share that the functionality of rendering an item search result on a map directly and loading tiles for a specific item id are available in our current system and may support solving this problem.

**Example**
1. STAC API search for all items on August 15
```
curl -X 'GET' \
  'https://dev.ghg.center/api/stac/search?collections=nasa-jpl-plumes-emissions-updated&datetime=2022-08-01T00%3A00%3A00.000Z%2F2022-08-15T23%3A59%3A59.999Z&limit=50' \
  -H 'accept: application/geo+json' -o emit-aug15.json
```

2. Choose item from feature collection on map
<img width="622" alt="select-footprint" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/3386265/46d621d7-5996-466d-bc35-b9fb18c6c648">

3. Construct RASTER API tiles url from collection and item id 
- collection=nasa-jpl-plumes-emissions-updated
- item=emit20220815t105833_o22707_s001_l1b_ch4mf_b0106_v01_mv0_p1_20220815
- `/api/raster/stac/tiles/{TileMatrixSetId}/{z}/{x}/{y}@{scale}x.{format}`
- http://dev.ghg.center/api/raster/stac/tiles/WebMercatorQuad/11/1329/780@1x?collection=nasa-jpl-plumes-emissions-updated&item=emit20220815t105833_o22707_s001_l1b_ch4mf_b0106_v01_mv0_p1_20220815&assets=ch4-plume-emissions&nodata=-9999&rescale=1,1500&colormap_name=plasma
<img width="297" alt="example-tile" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/3386265/4a6c0961-deeb-476b-ab1e-be3575a73fb3">

**Comment by jsignell** [comment]
Ok I have a rough version here: https://jsignell.github.io/voici/voici/render/plumes.html

Logistical steps:
 - [ ] set up a VEDA repo and move interactive viz to there
 
Data:
- [ ] data are currently in a gist that I downloaded from google drive - need a better solution -> maybe for now they can be stored in the github repo where the viz will live.

Viz improvements:
 - [ ] Only add a given raster once
 - [ ] Add a colorbar
 - [ ] (maybe) Set up query param parsing so that you can copy a link to an exact plume
 - [ ] (maybe) Add a human readable name to the plumes

**Comment by j08lue** [comment]
> need a better solution
If we embed this view into a page in the GHG Center Dashboard UI, we could include it as an asset alongside that, as we do with CSV files of time series rendered in stories, etc. 🤷 Not ideal either - just one option.

**Comment by jsignell** [comment]
Ok I set up https://github.com/NASA-IMPACT/veda-interactive-emission-plumes somehow I created it in such a way that I didn't give myself admin access so I can't set up github pages.

**Comment by j08lue** [comment]
Oops. I asked Iksha for help, will let you know when it is resolved.

**Comment by jsignell** [comment]
@slesaad rescued me :)

**Comment by j08lue** [comment]
For the GHG Center, we have worked out a different solution than WASM-compiled notebooks, because fast initial loading time was critical and styling needed to be harmonized with the rest of the UI and other embedded apps.

Bit of a quick decision. We can discuss use cases when Python-based apps are better solutions, design guidelines, etc.

https://github.com/NASA-IMPACT/interactive-emission-plumes
