### ISSUE TITLE
Add "BETA" to GHGC Website Header that links to development & contributing page

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-config-ghg#69]
Requesting implementation of BETA button next to GHGC Header/title that hyperlinks to a "Development & Contributing" page (or similar), just like the VEDA Dashboard (see below). 
BETA Button: 
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/98853455/4a2b1a96-c49c-4f03-b62a-29adadac0a2e)
[Development & Contributing Page](https://www.earthdata.nasa.gov/dashboard/development)

Deborah / team to help provide content?
For R1, include only feedback button at bottom of Dev & Contr. page.

**Comment by jerikac** [comment]
@j08lue Are you able to help assign this issue to team members?

**Comment by j08lue** [comment]
Sure, let me try to translate this back to a user need:

_As a user of the GHG Center website, I want to be notified that the website is in beta stage and have access to information about what that means for the quality of the content as well as possible ways for me to report issues / give feedback, so I know what to expect from the website._

Something like that?

I would pass this on to design to see how we best solve this for the GHG center - whether it is a button somewhere or what - I am sure we can find a solution that works well.

We currently do not have the content for a "Development & Contributing" page for the GHG Center. What should it say on that page - apart from a link to the feedback forms?

**Comment by jerikac** [comment]
Suggested (draft) content: 
"The current GHG Center Dashboard reflects an initial (v0.1) release of the platform that is subject to change with subsequent releases and updates.

This GHG Center dashboard is built by the [NASA Earth Science Data Systems program](https://earthdata.nasa.gov/) in collaboration with science teams and data providers from EPA, NIST, and NOAA. We are grateful for the many third-party open source projects that have been used to develop and contribute to the GHG Center.

We welcome your feedback to help improve the GHG Center Dashboard. To do so, select the feedback button below or navigate to the Feedback button throughout the website."

**Comment by faustoperez** [comment]
Hi @jerikac and all, here's a proposal for the BETA button next to the GHGC logo

<img width="773" alt="image" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/12268629/7776cafb-9e0e-47d5-b13b-fc36f31a204f">

@danielfdsilva please find the Figma file here 👉 https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=222%3A2817&mode=design&t=RsPPIettK2EfI3i3-1

**Comment by jerikac** [comment]
Requested changes to language: 
The current US GHG Center platform reflects an initial (v0.8.0) release that is subject to enhancements through future releases and updates.

This US GHG Center platform is a collaborative effort involving equal contributions from EPA, NASA, NIST, and NOAA. We are grateful for the many third-party open source projects that have been used to develop and contribute to the US GHG Center.

We welcome your feedback to help improve the platform. To share your thoughts, please click on the feedback button below or find the Feedback button available across the website.
