### ISSUE TITLE
Can we have password protection on production site (until public launch)?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#73]
We currently have password protection on https://ghg-demo.netlify.app/ to keep the page from getting indexed and be publicly viewable. Password protection is done with a convenient feature from Netlify.

Can we have password protection also on the production (S3-based) deployment at https://ghg.center, until public launch?

Related to #72

## Acceptance criteria

- [ ] Figured out how to have a password-protected site at https://ghg.center

**Comment by j08lue** [comment]
Somehow, https://ghg.center/ currently has password protection. @slesaad probably knows how?

Probably something that can be solved with CloudFront or something?

**Comment by slesaad** [comment]
I added a very simple version of password protection because deborah asked for it, i'm sure it's not done the best way :D @j08lue

**Comment by j08lue** [comment]
Right. We need to set this up server-side, I guess, otherwise it will not be very effective either.

Can you take care of that, @slesaad or @amarouane-ABDELHAK, or should we ask the Dashboard team?

**Comment by slesaad** [comment]
@j08lue i'd ask the dashboard team since it's a `veda-ui` change

**Comment by j08lue** [comment]
> since it's a `veda-ui` change

It could be, but perhaps a server-side solution would be better, because it cannot be circumvented. Seems like you could put a CloudFront CDN in front of the bucket: https://jamesthom.as/2022/10/password-protection-for-static-websites-on-aws-s3/

**Comment by amarouane-ABDELHAK** [comment]
Should the deployment be in MCP or it can be in a less restricted accounts like SMCE/UAH? will it be acceptable to use cognito for authentication?

**Comment by j08lue** [comment]
Good question - I would think that it ultimately needs to be in MCP, but until public release, maybe SMCE is fine. We do not need different users, just a simple password, like we have on the demo deployment.

**Comment by amarouane-ABDELHAK** [comment]
I was thinking just create one user and share it, no need for multiple users.

**Comment by slesaad** [comment]
Added simple http authorization with user and password to staging and prod site. Should work for now.
<img width="1044" alt="image" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/7830949/307f9277-e488-4f55-918a-2ea743b37793">

**Comment by slesaad** [comment]
should be ok to close
