### ISSUE TITLE
Update GHG design based on 6th September feedback

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#88]
Complete feedback in [doc](https://docs.google.com/document/d/1MrWh83UmU_7D7NfOv4nihc_4RXiAIM_w4aGW3H15YGM/edit#bookmark=id.15qxpb8ydgx)

1. Main nav items are not self-explanatory (suggestion: hover text)
2. Much of the text is very small on a regular high-res screen, in particular on cards (suggestion: bigger text)
3. Revise "Welcome" text layout - feedback: looks orphaned, left-aligned
4. Can we have banner/hero images on other pages than home, like About, Data Insights, etc?
5. Update [footer content](https://docs.google.com/document/d/1MrWh83UmU_7D7NfOv4nihc_4RXiAIM_w4aGW3H15YGM/edit#bookmark=id.il909wauqdl6)

## Acceptance criteria

- [x] Responded to the above requests, indicating the response for each, here or in the doc

**Comment by j08lue** [comment]
Updated design:

https://drive.google.com/file/d/1eTi3UCkwm9I3FWB1Xh_D4UvhVH_fN1F2/view


###Re 1 (not self-explanatory nav items):

- [x] Replaced "Analysis" with "Data Analysis"

We did not implement hover texts because this is not common practice and does not work on mobile.


### Re 2 (font size on flow text):

- [x] Increased font size on cards and welcome text


### Re 3 ("Welcome" text layout):

- [x] Moved into more centered text block

Did not just center everything for design reasons.


### Re 4 (banner images):

- [ ] Received images, going to process and add


### Re 5 (footer content):

- [x] Done.

**Comment by j08lue** [comment]
Implemented in 
- #116

**Comment by jerikac** [comment]
Is it possible to update the footer text to also say "Data Analysis", as we've done with the top-bar nav items? 
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/98853455/9d6a8949-b11a-419a-9488-8fd3e11997b8)

**Comment by jerikac** [comment]
Also a note to help close this issue - the suggestion to include banner images for the data analysis, data insights, and data catalog pages has been rejected. We've also been asked to remove the banner image that is up for the Beta Page

**Comment by slesaad** [comment]
@j08lue we've decided to not add banner images on the other pages, so that can be crossed out!

**Comment by slesaad** [comment]
Renamed analysis -> data analysis and removed the banner image from beta page - https://github.com/NASA-IMPACT/veda-config-ghg/pull/122
