### ISSUE TITLE
Put intro to GHG Center first among list of Data Insights

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#92]
The Intro to GHG Center should be first, before the other stories.

First suggestion: use the existing feature to pin the Intro story as "Featured Data Insight".

If that is not accepted, consider ordering stories by date by default and make the intro story most recent / oldest.

## Acceptance criteria

- [x] Intro story is the first one users see

**Comment by slesaad** [comment]
https://github.com/NASA-IMPACT/veda-config-ghg/pull/97
