### ISSUE TITLE
Add missing thumbnails on Data Insights

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#93]
Missing thumbnails for "Intro to GHGC" and "How GHGC tracks Carbon"

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/4db725c3-6ef1-4c76-b951-3cb9f44d9c2f)

## Acceptance criteria

- [ ] Provided images @deborahUAH 
- [ ] Added missing thumbnails

**Comment by slesaad** [comment]
These have been added already
