### ISSUE TITLE
Should links to external applications always open in new tabs?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#94]
The "Hub" link and some others that reference resources external to the GHG Center website currently open in the same tab/window. Is that how it should be?

## Acceptance criteria

- [x] Provided guidance on this question from a design perspective (reference to external material is ok)
- [x] Presented to stakeholders

**Comment by hanbyul-here** [comment]
Opening a new tab is a practice generally to refrain from. A few of the reasons why would be

1. Creating clutters/disorientation for users. 
2. Making a user lose control of the tab (losing the means of going back. Also, a user usually has the means to open a new tab on their own.) 
3. Lowering accessibility for low-vision users

More full explanation can be found through this link: https://www.nngroup.com/articles/new-browser-windows-and-tabs/

W3C has a guide on when to open a new tab in a new window (from accessibility view): https://www.w3.org/TR/WCAG20-TECHS/G200.html The link above https://www.nngroup.com/articles/new-browser-windows-and-tabs/ adds two more cases (with a lot of caution) 

When to open a link in a new tab

1. When the contents of the new tab are required to complete a task from the existing page - Does the documentation fall into this category? I am not sure but maybe? 
2. It's a link to a different content type (like PDF).
3. It will keep users on the site. (This might be difficult to prove in Veda with a low number of users.)

There are some practices recommended for a new tab too such as an icon that indicates the link will open in a new tab. 

Ideally, we should evaluate if a request for a new tab can fall into any of the 3 criteria above, (There will be still a grey area such as the documentation case mentioned above.) and have a design approach to indicate to users that the link opens in a new tab.

**Comment by j08lue** [comment]
Thanks for the great references, @hanbyul-here.

I think we should follow the general guidance from [W3C](https://www.w3.org/TR/WCAG20-TECHS/G200.html) as a recognized source to avoid opening links in new tabs, for the reasons stated there.


## Only exception: single reasonable workflow

The only exception is when leaving the site would break the single / by far most reasonable **workflow**.

As the referenced sources explain, such a workflow would be that users need to complete a task in an external source / different content type and then continue with other steps on the original site, or need the external resource side-by-side with the original site. This has rarely been the case and if it occurs, we should ideally build the workflow into our site and not use browser features.

An example where we have such a workflow is our feedback form, which users are expected to open and then close as a natural conclusion (submit or cancel). We put that form into a modal on top of the site, so when users exit it, they are still on the site, since opening and completing the form does not imply the wish to leave (hopefully!). If the form instead of Google Forms was a page in our website (like a support center or so), we would not even open it separately / as an overlay, I think.

**Comment by j08lue** [comment]
I copied this information also into [project docs](https://docs.google.com/document/d/1ntbT044FQdUlWzYAgK49_jd85YtYFbt3SMhOIpChB_w/edit) for posterity. Closing here and hope it gets found when needed.
