### ISSUE TITLE
Add disclaimer to Analysis feature

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#95]
The Analysis feature received a lot of comments for not being documented enough and can possibly create more confusion than it helps, for non-scientific users.

Either we add some explanations and disclaimers to it, or we remove / hide it.

## Acceptance criteria

- [x] Decided what to do
- [x] Did it

**Comment by j08lue** [comment]
Decision was to keep the Analysis page, because it is a valuable feature for advanced users of the application.

**Comment by faustoperez** [comment]
Here's a design proposal for the disclaimer modal:


![Image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/12268629/57e893ae-676c-4db0-ba1c-a67ee940928e)

**Comment by j08lue** [comment]
Would the checkbox be ticked by default, @faustoperez - considering the goal @nerik mentioned to limit the number of clicks for most users?

**Comment by faustoperez** [comment]
> Would the checkbox be ticked by default, @faustoperez - considering the goal @nerik mentioned to limit the number of clicks for most users?

Yes, that's what I think the default behaviour should be 👍

**Comment by nerik** [comment]
@j08lue @faustoperez In [this document](https://docs.google.com/document/d/13qlcFe-WMY2dn8x895Difo4g0f-LHFB0xNEPg_cb5ks/edit#heading=h.e5xak3vv4x0l) there seems to be a generic app-wide disclaimer as well as specific page disclaimers. Which one should show up upon entering a specific page?

**Comment by j08lue** [comment]
Page-specific disclaimers, please.

**Comment by j08lue** [comment]
During review of the design today, it became clear that the Analysis page will require a more persistent / prominent explanation of the results the user is seeing, which they cannot click away.

The explanation should be shown in close proximity / context to the results, when they appear, so the users are sure to read them when looking at the data.

Text tbd.

**Comment by j08lue** [comment]
Done for all internal tools, only hub missing, ticketed separately:

- https://github.com/NASA-IMPACT/veda-config-ghg/issues/153
